mybatis:
  mapper-locations: classpath:mps/*.xml
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.103:3306/mgj
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 30
    minIdle: 20
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  resources:
    static-locations: classpath:/public,classpath:/static,file:c:/aaa
server:
  servlet:
    context-path: /mgj
  port: 8087   
    
    