sdk:
  alipay:
    dev: true #默认false,为true表示使用沙箱环境
    sign-type: RSA2 #签名算法
    app-id: 2016081900289943 #应用ID
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCXqcXmonOnBKVuuDZIklZxSfE5Jrc9Xyos7ul4pZgGGkNcvu8dPyLtNLN1uEWjTOd8Sapn4fVhozWvVPcZJzPFOgharFMwPXY9kajXaC4pzwW843l8fWh0GQXoA+jWy5GXf6A4c1PQzxm+UWHzcGTImv4GXj3To56xQaZS/l/a1WbSmgPwwMLwxVblAr7DeC8NGVX03ZK2+Lr5BRcMK0KIgfEmW/ZB4InjpiXl9EpU1aSNs91gIQHlXScBADAThz4wKq3XKywPi3sAaCgV5uI2PYntSCZpmOTuWdJOUksNmXQ63owuGVNdUaZsDExp6Btl/Ukhk39GIp6o12feq3J9AgMBAAECggEAA5+86Nvs44rK4TBpq6ZDhoV7zB/OtRq3CUfUMFvUnCC4h1jQoeRGU2C1ARUcJODLjz67YawWjvS1bbEcDm/PXuEaHgCMJFTzpFj8rdkBcWJPAsp0trLQciW+7GJbh/ZpTjNwgqjO0eiA9vk+2/BNmDWL6F8MHyiDvDyTWtxVMgdp9ivZaMO71noGk5juz0mJeVaoeATw+/oxz3QN3VdBa6NjPomL35lJ+TIuY/ammp5TZKuRlmKqN5/GT4slGOh3vPRRo5HVdcn69HsHGAF+i7UZS4ys4QSKISmmkHePzHwuGz6lHVzmz3kNrNSLaN5yZhcLmt01dY5DNDVQp6FJQQKBgQDOmwMgkf5lKFmF9LLwOlLPdJmCZa9MuqzyB+XLZ0I3X/vwsJhslB5qm3ljLkICsp+i1QmrZr1SXieAb6tUYZLG1z+of/s5E63hmw/YUqAlqEDhHC9NCcUtdCT7udUGIXkeIrw+nkBuz2KZ1/Z2N5XMKMszTfA5zBPNXM+/+0wC2QKBgQC77BhtkZODrKcmAbhdDIWy0wBZK47ixS0WKLm57KfbRx/ZkMVuroySnXufYjFeo7GXTPEZyZ0hQjmVrYm4DJcuNJ4XV0YDZJSReUqmPCabAnA8Kgga0GRd8UBTdG2IRBQkfgTRpcAENQa6iJsxLxNUDjTALmVs6ZevN6yfj1teRQKBgFzhBtjfiPPE3eoAhWjFb3DfxBsAx3vA9/qeXknAk939Am/Dk+JL/BiE6F8T7ozz7BvxlbU+LKIYvb1ZdjYq3ycQoQeI8VFJbYPch5UCIAiNyQzp9MG3QLMcYXvgoMluxtorV2D3F5Q5GuR6V8vxVSBAvojD4ti4y7YooSR3PkaRAoGAZeBrqdLW/vZ1s0QRd9hXDwgW00Cq+MNeWvn/Hg1vPpBDcwZqEkPsj3tyzohELYNevqCGwK0tUx986mknFTE2MGV0I0E8ApDffjIcRxyq7TQYNnWu6SJ6lvc4IUYoL0yBAvuSjzllbKJ2oF94iuRzfQkqjdlZQP8uLV5oZiQoq2UCgYBZWFQJumaffP6fG2yVjSGLjwUFc4prizFeuVEk0CD0MZ9iZQfxViJIwMt24y8F4YYyKrBrp66NxRge8QcDAug+akqsGHW7B2VPyfCE/9abRM7cLEyq82LYnAsIE/W/mmS3t0/0WQj7cihRXt73sO/uNDZUdiTUINl9kPg3rcIOhA== #应用私钥
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1pk7l9YAXVkbKUQF1yi5thNa3p1OAUVgLqGRjvkgJyM5MkPRWqBTp+oap2yPqasJtIU95qde6U7v+PctRmr3WZKaAhRN3LQe3LmjfdcQ9YX66wA5IumuTYw173FZjExESti2dR/Bh2vRoqS8bHyy5a15Uk6EGWgN07VRnmsz1UXxl7bfQNpupDTrUzYRPOH1ca8VE50h/Ogm9NrdcTnuYNSaUa56qUf+Fg2XN7SSli5VpGuhU1qdYJxtPjtR2Fb/qjTivCg5cfWBtzKXavZ00w/V1zoLIHUUOf+vCojTJH3dGCkLVfQf7MpzJxEb0mKedCzA+9W94fci3jFE7XJHaQIDAQAB #支付宝公钥


mybatis:
  mapper-locations: classpath:mps/*.xml
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.103:3306/mgj
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 30
    minIdle: 20
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  resources:
    static-locations: classpath:/public,classpath:/static,file:c:/aaa
server:
  servlet:
    context-path: /mgj
  port: 8087   
    
    